export const ADD_COORDONNEES = "ADD_COORDONNEES";
export const ADD_FORMATIONS="ADD_FORMATIONS";
export const ADD_EXPERIENCES="ADD_EXPERIENCES";
export const ADD_COMPETENCES="ADD_COMPETENCES";
export const ACTIVE_STEP = "ACTIVE_STEP";